services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluez-luxoria-app
    restart: always
    ports:
      - "${APP_PORT:-3001}:80"
    environment:
      - NODE_ENV=production
